### ISSUE TITLE
Using @PreStateChange(to = ToState.class) will cause compile error

### ISSUE THREAD

**Issue by zhongdj** [zhongdj/Lifecycle#7]
State Class is Valid, and can be processed with @PostStateChange(to = ToState.class), but not @PreStateChange

FINE: com.eventbank.membership.biz.impl.MembershipApplication
Exception in thread "main" net.imadz.verification.VerificationException: 002-3700(For callback method public void com.eventbank.membership.biz.impl.MembershipApplication.onCompleted(net.imadz.lifecycle.LifecycleContext) with @PreStateChange annotation, it will not be invoked, as no state will definitely transit @to state class com.eventbank.membership.lifecycle.MembershipApplicationLifecycle$States$Completed.  )
	at net.imadz.lifecycle.meta.builder.impl.StateMachineObjectBuilderImpl.verifyCallbackMethods(StateMachineObjectBuilderImpl.java:1121)
	at net.imadz.lifecycle.meta.builder.impl.StateMachineObjectBuilderImpl.verifySyntax(StateMachineObjectBuilderImpl.java:1502)
	at net.imadz.lifecycle.meta.builder.impl.StateMachineObjectBuilderImpl.build(StateMachineObjectBuilderImpl.java:182)
	at net.imadz.lifecycle.meta.builder.impl.StateMachineMetaBuilderImpl.newInstance(StateMachineMetaBuilderImpl.java:178)
	at net.imadz.lifecycle.AbsStateMachineRegistry.registerLifecycleMeta(AbsStateMachineRegistry.java:203)
	at net.imadz.lifecycle.AbsStateMachineRegistry.registerLifecycleMeta(AbsStateMachineRegistry.java:167)
	at net.imadz.lifecycle.AbsStateMachineRegistry.loadStateMachineObject(AbsStateMachineRegistry.java:309)
	at net.imadz.lifecycle.StaticWeaver.weaveClass(StaticWeaver.java:84)
	at net.imadz.lifecycle.StaticWeaver.processFolder(StaticWeaver.java:75)
	at net.imadz.lifecycle.StaticWeaver.processFolder(StaticWeaver.java:73)
	at net.imadz.lifecycle.StaticWeaver.processFolder(StaticWeaver.java:73)
	at net.imadz.lifecycle.StaticWeaver.processFolder(StaticWeaver.java:73)
	at net.imadz.lifecycle.StaticWeaver.processFolder(StaticWeaver.java:73)
	at net.imadz.lifecycle.StaticWeaver.processFolder(StaticWeaver.java:73)
	at net.imadz.lifecycle.StaticWeaver.main(StaticWeaver.java:67)
[trace] Stack trace suppressed: run last membership-impl/compile:compile for the full output.
[error] (membership-impl/compile:compile) Nonzero exit value: 1
[error] Total time: 16 s, completed Jan 7, 2015 9:54:27 PM

**Comment by zhongdj** [comment]
Not a bug. In that case, the toState cannot be predicated at pre state chagne
